version: '3'

services:
  radiobot:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - radiobot.env
    command: python3 -u main.py
    restart: always
  relay:
    image: infiniteproject/icecast
    env_file:
      - relay.env
    ports:
      - 8000:8000
    restart: always

